### Numpy

In [25]:
import numpy as np
import datetime

### E1

Create a 1D numpy array of numbers from 1 to 9 without manually typing numbers.

Keyword: Range

In [3]:
#E1 Desired Output:
#array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr=np.array(range(10))

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### E2

Extract all odd numbers from the given array

Keyword: Filter



In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#E2 Desired Output:
# [1, 3, 5, 7, 9]
# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
    if element%2!=0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False, True, False, True]
[1 3 5 7 9]


### E3

Replace all odd numbers in the given array with -1

Keyword: Filter, Replace

In [21]:
arr[arr%2==1]=-1

In [22]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [16]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
#E3 Desired Output
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### E4

Conver the given 1D array to 2D array with two rows

Keyword: Reshape

In [16]:
arr = np.arange(10)

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#E4 Desired Output
#array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
newarr=arr.reshape(2,5)
print(newarr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### E5

Find common items in a and b

Keyword: instersect

In [20]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


In [23]:
#E5 Desired Output
#array([2, 4])
new=np.intersect1d(a,b)

In [24]:
new

array([2, 4])

### E6 

Get items between 5 and 10 from the given array



In [25]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [28]:
#E6 Desired Output
#(array([6, 9, 10]),)
filter_arr = []

# go through each element in arr
for element in a:
    if element>=5 and element<=10:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = a[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, True, False, False]
[ 6  9 10]


### E7

a. Find the sum, max value of all the values in the given numpy array


b. FInd the maximum value in each column in the given array

Keyword: Sum, Max

In [38]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
            [0.54627315, 0.05093587, 0.40067661, 0.55645993],
             [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [30]:
a.sum()

4.8595784

In [31]:
a.max()

0.82485143

In [36]:
a.max(0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [48]:
#E8 Desired Output

#array([[4.5053314, 1.7296777, 3.4376245, 5.510652 ],[5.4627315, 0.5093587, 4.0067661, 5.5645993],[1.2697628, 8.2485143, 2.6590556, 5.6917101]])

### E8

Use a function to multiply all the value of the array by 10

In [44]:
b=np.array([10])

In [45]:
c=a*b

In [41]:
c

array([[4.5053314, 1.7296777, 3.4376245, 5.510652 ],
       [5.4627315, 0.5093587, 4.0067661, 5.5645993],
       [1.2697628, 8.2485143, 2.6590556, 5.6917101]])

In [46]:
d=10*a

In [47]:
d

array([[4.5053314, 1.7296777, 3.4376245, 5.510652 ],
       [5.4627315, 0.5093587, 4.0067661, 5.5645993],
       [1.2697628, 8.2485143, 2.6590556, 5.6917101]])

### Pandas

In [2]:
import pandas as pd

In [3]:
log_data = pd.read_csv('data\log_data_csv.csv')

In [4]:
log_data

DEPTH  ABDCQF01  ABDCQF02  ABDCQF03  ABDCQF04    BS  CALI  DRHO  DT  \
0       145.9       NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN   
1       146.0       NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN   
2       146.1       NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN   
3       146.2       NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN   
4       146.3       NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN   
...       ...       ...       ...       ...       ...   ...   ...   ...  ..   
33186  3464.5       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN   
33187  3464.6       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN   
33188  3464.7       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN   
33189  3464.8       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN   
33190  3464.9       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN   

       DTS  ...  PEF  RACEHM  RACELM  RD  RHOB  RM      ROP  RPCEHM  RPCELM  \
0      NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   
1      NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   
2      NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   
3      NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   
4      NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   
...    ...  ...  ...     ...     ...  ..   ...  ..      ...     ...     ...   
33186  NaN  ...  NaN     NaN     NaN NaN   NaN NaN  29.9836     NaN     NaN   
33187  NaN  ...  NaN     NaN     NaN NaN   NaN NaN  29.9767     NaN     NaN   
33188  NaN  ...  NaN     NaN     NaN NaN   NaN NaN  29.9699     NaN     NaN   
33189  NaN  ...  NaN     NaN     NaN NaN   NaN NaN  29.9903     NaN     NaN   
33190  NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   

       RT  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
...    ..  
33186 NaN  
33187 NaN  
33188 NaN  
33189 NaN  
33190 NaN  

[33191 rows x 23 columns]

### E9

Convert Depth column into index of pandas (log_data)

Keyword: Index 

In [54]:
log_data.set_index('DEPTH')

ABDCQF01  ABDCQF02  ABDCQF03  ABDCQF04    BS  CALI  DRHO  DT  DTS  GR  \
DEPTH                                                                           
145.9        NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN  NaN NaN   
146.0        NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN  NaN NaN   
146.1        NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN  NaN NaN   
146.2        NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN  NaN NaN   
146.3        NaN       NaN       NaN       NaN  36.0   NaN   NaN NaN  NaN NaN   
...          ...       ...       ...       ...   ...   ...   ...  ..  ...  ..   
3464.5       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN  NaN NaN   
3464.6       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN  NaN NaN   
3464.7       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN  NaN NaN   
3464.8       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN  NaN NaN   
3464.9       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN  NaN NaN   

        ...  PEF  RACEHM  RACELM  RD  RHOB  RM      ROP  RPCEHM  RPCELM  RT  
DEPTH   ...                                                                  
145.9   ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  
146.0   ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  
146.1   ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  
146.2   ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  
146.3   ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  
...     ...  ...     ...     ...  ..   ...  ..      ...     ...     ...  ..  
3464.5  ...  NaN     NaN     NaN NaN   NaN NaN  29.9836     NaN     NaN NaN  
3464.6  ...  NaN     NaN     NaN NaN   NaN NaN  29.9767     NaN     NaN NaN  
3464.7  ...  NaN     NaN     NaN NaN   NaN NaN  29.9699     NaN     NaN NaN  
3464.8  ...  NaN     NaN     NaN NaN   NaN NaN  29.9903     NaN     NaN NaN  
3464.9  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN NaN  

[33191 rows x 22 columns]

### E10

Convert 'BS' column of pandas into a numpy array

In [27]:
np.array(log_data['BS'])

array([36. , 36. , 36. , ...,  8.5,  8.5,  8.5])

In [36]:
#E10 Desired Output

#array([36. , 36. , 36. , ...,  8.5,  8.5,  8.5])

### E11

#Find the frequency of unique values present in 'BS' column in pandas

Keyword: value counts

In [29]:
log_data['BS'].value_counts()

17.5000    12469
26.0000    11289
12.2500     4827
8.5000      3800
36.0000      800
12.2283        2
8.5217         1
25.9508        1
17.4696        1
35.9421        1
Name: BS, dtype: int64

### E12

Find the Number of unique values in 'BS' column in pandas

Keyword: nunique

In [30]:
log_data['BS'].nunique()

10

### E13 

Find the minimum, 25th percentile, median, 75th percentile and maximum value of 'GR' column in pandas

Keyword: Quantile


In [31]:
log_data['GR'].quantile(0.25)

29.481175

In [32]:
log_data['GR'].quantile(0.75)

79.2472

In [38]:
log_data['GR'].quantile(0.5)
# gives same value as median

58.005700000000004

In [34]:
log_data['GR'].max()

297.7673

In [35]:
log_data['GR'].median()


58.005700000000004

In [37]:
log_data['GR'].quantile(1)
# gives maximum value

297.7673

### E14


Replace Bit Size of value 36 to 40 in log_data


Keyword: Filter and Replace

In [6]:
log_data['BS']=log_data['BS'].replace([36],40.0)

In [7]:
log_data

DEPTH  ABDCQF01  ABDCQF02  ABDCQF03  ABDCQF04    BS  CALI  DRHO  DT  \
0       145.9       NaN       NaN       NaN       NaN  40.0   NaN   NaN NaN   
1       146.0       NaN       NaN       NaN       NaN  40.0   NaN   NaN NaN   
2       146.1       NaN       NaN       NaN       NaN  40.0   NaN   NaN NaN   
3       146.2       NaN       NaN       NaN       NaN  40.0   NaN   NaN NaN   
4       146.3       NaN       NaN       NaN       NaN  40.0   NaN   NaN NaN   
...       ...       ...       ...       ...       ...   ...   ...   ...  ..   
33186  3464.5       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN   
33187  3464.6       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN   
33188  3464.7       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN   
33189  3464.8       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN   
33190  3464.9       NaN       NaN       NaN       NaN   8.5   NaN   NaN NaN   

       DTS  ...  PEF  RACEHM  RACELM  RD  RHOB  RM      ROP  RPCEHM  RPCELM  \
0      NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   
1      NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   
2      NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   
3      NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   
4      NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   
...    ...  ...  ...     ...     ...  ..   ...  ..      ...     ...     ...   
33186  NaN  ...  NaN     NaN     NaN NaN   NaN NaN  29.9836     NaN     NaN   
33187  NaN  ...  NaN     NaN     NaN NaN   NaN NaN  29.9767     NaN     NaN   
33188  NaN  ...  NaN     NaN     NaN NaN   NaN NaN  29.9699     NaN     NaN   
33189  NaN  ...  NaN     NaN     NaN NaN   NaN NaN  29.9903     NaN     NaN   
33190  NaN  ...  NaN     NaN     NaN NaN   NaN NaN      NaN     NaN     NaN   

       RT  
0     NaN  
1     NaN  
2     NaN  
3     NaN  
4     NaN  
...    ..  
33186 NaN  
33187 NaN  
33188 NaN  
33189 NaN  
33190 NaN  

[33191 rows x 23 columns]

### E15

Get the column types of the below pandas and delete the column Unnamed: 0   

Keyword: dtypes

In [30]:
production_data = pd.read_csv('data/prod_data.csv')


In [31]:

production_data


Unnamed: 0     DATEPRD  AVG_DOWNHOLE_PRESSURE  \
0               0  2014-04-07                0.00000   
1               1  2014-04-08                    NaN   
2               2  2014-04-09                    NaN   
3               3  2014-04-10                    NaN   
4               4  2014-04-11              310.37614   
...           ...         ...                    ...   
15629       15629  2016-09-14                    NaN   
15630       15630  2016-09-15                    NaN   
15631       15631  2016-09-16                    NaN   
15632       15632  2016-09-17                    NaN   
15633       15633  2016-09-18                    NaN   

       AVG_DOWNHOLE_TEMPERATURE  AVG_DP_TUBING  AVG_ANNULUS_PRESS  \
0                       0.00000        0.00000            0.00000   
1                           NaN            NaN            0.00000   
2                           NaN            NaN            0.00000   
3                           NaN            NaN            0.00000   
4                      96.87589      277.27826            0.00000   
...                         ...            ...                ...   
15629                       NaN            NaN            0.27272   
15630                       NaN            NaN            0.28686   
15631                       NaN            NaN            0.28604   
15632                       NaN            NaN            0.27212   
15633                       NaN            NaN                NaN   

       AVG_CHOKE_SIZE_P AVG_CHOKE_UOM  AVG_WHP_P  AVG_WHT_P  DP_CHOKE_SIZE  \
0              0.000000             %    0.00000    0.00000        0.00000   
1              1.003059             %    0.00000    0.00000        0.00000   
2              0.979008             %    0.00000    0.00000        0.00000   
3              0.545759             %    0.00000    0.00000        0.00000   
4              1.215987             %   33.09788   10.47992       33.07195   
...                 ...           ...        ...        ...            ...   
15629          0.636088             %    0.07776    0.22879        0.01862   
15630          0.670794             %    0.08545    0.22914        0.00631   
15631          0.664393             %    0.08544    0.22896        0.01181   
15632          0.624660             %    0.07497    0.22846        0.02576   
15633               NaN           NaN        NaN        NaN        0.00000   

       BORE_OIL_VOL  BORE_GAS_VOL  BORE_WAT_VOL  BORE_WI_VOL   FLOW_KIND  \
0               0.0           0.0           0.0          NaN  production   
1               0.0           0.0           0.0          NaN  production   
2               0.0           0.0           0.0          NaN  production   
3               0.0           0.0           0.0          NaN  production   
4               0.0           0.0           0.0          NaN  production   
...             ...           ...           ...          ...         ...   
15629           0.0           0.0           0.0          NaN  production   
15630           0.0           0.0           0.0          NaN  production   
15631           0.0           0.0           0.0          NaN  production   
15632           0.0           0.0           0.0          NaN  production   
15633           NaN           NaN           NaN          0.0   injection   

      WELL_TYPE  
0            WI  
1            OP  
2            OP  
3            OP  
4            OP  
...         ...  
15629        OP  
15630        OP  
15631        OP  
15632        OP  
15633        WI  

[15634 rows x 17 columns]

In [32]:
production_data.dtypes

Unnamed: 0                    int64
DATEPRD                      object
AVG_DOWNHOLE_PRESSURE       float64
AVG_DOWNHOLE_TEMPERATURE    float64
AVG_DP_TUBING               float64
AVG_ANNULUS_PRESS           float64
AVG_CHOKE_SIZE_P            float64
AVG_CHOKE_UOM                object
AVG_WHP_P                   float64
AVG_WHT_P                   float64
DP_CHOKE_SIZE               float64
BORE_OIL_VOL                float64
BORE_GAS_VOL                float64
BORE_WAT_VOL                float64
BORE_WI_VOL                 float64
FLOW_KIND                    object
WELL_TYPE                    object
dtype: object

In [33]:
del production_data['Unnamed: 0']
production_data


DATEPRD  AVG_DOWNHOLE_PRESSURE  AVG_DOWNHOLE_TEMPERATURE  \
0      2014-04-07                0.00000                   0.00000   
1      2014-04-08                    NaN                       NaN   
2      2014-04-09                    NaN                       NaN   
3      2014-04-10                    NaN                       NaN   
4      2014-04-11              310.37614                  96.87589   
...           ...                    ...                       ...   
15629  2016-09-14                    NaN                       NaN   
15630  2016-09-15                    NaN                       NaN   
15631  2016-09-16                    NaN                       NaN   
15632  2016-09-17                    NaN                       NaN   
15633  2016-09-18                    NaN                       NaN   

       AVG_DP_TUBING  AVG_ANNULUS_PRESS  AVG_CHOKE_SIZE_P AVG_CHOKE_UOM  \
0            0.00000            0.00000          0.000000             %   
1                NaN            0.00000          1.003059             %   
2                NaN            0.00000          0.979008             %   
3                NaN            0.00000          0.545759             %   
4          277.27826            0.00000          1.215987             %   
...              ...                ...               ...           ...   
15629            NaN            0.27272          0.636088             %   
15630            NaN            0.28686          0.670794             %   
15631            NaN            0.28604          0.664393             %   
15632            NaN            0.27212          0.624660             %   
15633            NaN                NaN               NaN           NaN   

       AVG_WHP_P  AVG_WHT_P  DP_CHOKE_SIZE  BORE_OIL_VOL  BORE_GAS_VOL  \
0        0.00000    0.00000        0.00000           0.0           0.0   
1        0.00000    0.00000        0.00000           0.0           0.0   
2        0.00000    0.00000        0.00000           0.0           0.0   
3        0.00000    0.00000        0.00000           0.0           0.0   
4       33.09788   10.47992       33.07195           0.0           0.0   
...          ...        ...            ...           ...           ...   
15629    0.07776    0.22879        0.01862           0.0           0.0   
15630    0.08545    0.22914        0.00631           0.0           0.0   
15631    0.08544    0.22896        0.01181           0.0           0.0   
15632    0.07497    0.22846        0.02576           0.0           0.0   
15633        NaN        NaN        0.00000           NaN           NaN   

       BORE_WAT_VOL  BORE_WI_VOL   FLOW_KIND WELL_TYPE  
0               0.0          NaN  production        WI  
1               0.0          NaN  production        OP  
2               0.0          NaN  production        OP  
3               0.0          NaN  production        OP  
4               0.0          NaN  production        OP  
...             ...          ...         ...       ...  
15629           0.0          NaN  production        OP  
15630           0.0          NaN  production        OP  
15631           0.0          NaN  production        OP  
15632           0.0          NaN  production        OP  
15633           NaN          0.0   injection        WI  

[15634 rows x 16 columns]

### E16 

Convert the DATEPRD column into date-time format and replace DATEPRD column as pandas index


In [34]:
production_data['DATEPRD']=pd.to_datetime(production_data['DATEPRD'])

In [35]:
production_data['DATEPRD']

0       2014-04-07
1       2014-04-08
2       2014-04-09
3       2014-04-10
4       2014-04-11
           ...    
15629   2016-09-14
15630   2016-09-15
15631   2016-09-16
15632   2016-09-17
15633   2016-09-18
Name: DATEPRD, Length: 15634, dtype: datetime64[ns]

In [42]:
production_data.set_index('DATEPRD',inplace=True)
production_data

AVG_DOWNHOLE_PRESSURE  AVG_DOWNHOLE_TEMPERATURE  AVG_DP_TUBING  \
DATEPRD                                                                      
2014-04-07                0.00000                   0.00000        0.00000   
2014-04-08                    NaN                       NaN            NaN   
2014-04-09                    NaN                       NaN            NaN   
2014-04-10                    NaN                       NaN            NaN   
2014-04-11              310.37614                  96.87589      277.27826   
...                           ...                       ...            ...   
2016-09-14                    NaN                       NaN            NaN   
2016-09-15                    NaN                       NaN            NaN   
2016-09-16                    NaN                       NaN            NaN   
2016-09-17                    NaN                       NaN            NaN   
2016-09-18                    NaN                       NaN            NaN   

            AVG_ANNULUS_PRESS  AVG_CHOKE_SIZE_P AVG_CHOKE_UOM  AVG_WHP_P  \
DATEPRD                                                                    
2014-04-07            0.00000          0.000000             %    0.00000   
2014-04-08            0.00000          1.003059             %    0.00000   
2014-04-09            0.00000          0.979008             %    0.00000   
2014-04-10            0.00000          0.545759             %    0.00000   
2014-04-11            0.00000          1.215987             %   33.09788   
...                       ...               ...           ...        ...   
2016-09-14            0.27272          0.636088             %    0.07776   
2016-09-15            0.28686          0.670794             %    0.08545   
2016-09-16            0.28604          0.664393             %    0.08544   
2016-09-17            0.27212          0.624660             %    0.07497   
2016-09-18                NaN               NaN           NaN        NaN   

            AVG_WHT_P  DP_CHOKE_SIZE  BORE_OIL_VOL  BORE_GAS_VOL  \
DATEPRD                                                            
2014-04-07    0.00000        0.00000           0.0           0.0   
2014-04-08    0.00000        0.00000           0.0           0.0   
2014-04-09    0.00000        0.00000           0.0           0.0   
2014-04-10    0.00000        0.00000           0.0           0.0   
2014-04-11   10.47992       33.07195           0.0           0.0   
...               ...            ...           ...           ...   
2016-09-14    0.22879        0.01862           0.0           0.0   
2016-09-15    0.22914        0.00631           0.0           0.0   
2016-09-16    0.22896        0.01181           0.0           0.0   
2016-09-17    0.22846        0.02576           0.0           0.0   
2016-09-18        NaN        0.00000           NaN           NaN   

            BORE_WAT_VOL  BORE_WI_VOL   FLOW_KIND WELL_TYPE  
DATEPRD                                                      
2014-04-07           0.0          NaN  production        WI  
2014-04-08           0.0          NaN  production        OP  
2014-04-09           0.0          NaN  production        OP  
2014-04-10           0.0          NaN  production        OP  
2014-04-11           0.0          NaN  production        OP  
...                  ...          ...         ...       ...  
2016-09-14           0.0          NaN  production        OP  
2016-09-15           0.0          NaN  production        OP  
2016-09-16           0.0          NaN  production        OP  
2016-09-17           0.0          NaN  production        OP  
2016-09-18           NaN          0.0   injection        WI  

[15634 rows x 15 columns]

### E17

Groupby Pandas based on year and find the sum of all individual columns

Keyword: datetime index, year in datetime index

In [43]:
production_data.groupby(lambda y: (y.year)).sum()

AVG_DOWNHOLE_PRESSURE  AVG_DOWNHOLE_TEMPERATURE  AVG_DP_TUBING  \
2007               0.000000                  0.000000       0.000000   
2008          126332.310680              53145.321325   86636.465440   
2009          171879.218917              74141.591116  121894.132257   
2010          160502.923169              66601.974941  132274.102660   
2011           83850.168072              34777.523747   83890.420230   
2012           78690.519824              34035.076791   77876.822481   
2013          127489.850406              51721.968030  114485.516138   
2014          317179.952517             140112.726769  268830.071114   
2015          349952.670812             151552.452285  299224.777084   
2016          216721.126936              86834.829308  198066.197563   

      AVG_ANNULUS_PRESS  AVG_CHOKE_SIZE_P     AVG_WHP_P      AVG_WHT_P  \
2007           0.000000          0.000000      0.000000       0.000000   
2008        4025.115398      19763.257827  39695.845240   36453.959314   
2009        5621.077441      33456.352462  51945.817217   55808.568903   
2010        8348.346807      41160.007435  37669.600702   61336.154932   
2011        6295.671376      43363.813540  31970.430852   54738.515777   
2012        6526.369311      51541.883105  23937.162317   54169.571480   
2013       15130.560085      61802.833284  36129.971488   69116.398131   
2014       27382.392622      78508.192935  78982.288089  103858.640858   
2015       22921.257036      84959.735169  79663.878891  109971.042472   
2016       20963.840959      77492.073819  35438.862473   73991.462309   

      DP_CHOKE_SIZE  BORE_OIL_VOL  BORE_GAS_VOL  BORE_WAT_VOL   BORE_WI_VOL  
2007       0.000000          0.00  0.000000e+00          0.00  0.000000e+00  
2008   27182.395652    1764375.15  2.570386e+08      23508.94  2.417770e+06  
2009   29335.704672    2684392.04  3.759820e+08     232103.74  4.392198e+06  
2010   14810.973585    1689902.55  2.439484e+08    1887594.78  4.569394e+06  
2011   12759.319522     847965.40  1.303202e+08    2190640.28  3.442446e+06  
2012    5627.735295     574206.33  9.020864e+07    2109601.63  2.975214e+06  
2013   12179.211410     558012.53  8.758778e+07    2576365.79  3.453761e+06  
2014   32737.373560     743107.49  1.117919e+08    2716070.92  3.825493e+06  
2015   30608.753230     861749.06  1.284238e+08    2009825.86  3.201627e+06  
2016   10264.390093     313370.06  5.006913e+07    1572866.41  2.052229e+06